### ISSUE TITLE
[FEATURE] Tree-select

### ISSUE THREAD

**Issue by AnteaterKit** [TinkoffCreditSystems/taiga-ui#249]
# 🚀 Create tree-select component
Sometimes developers need to create forms with hierarchical select data.
Like this:
<img width="309" alt="Screenshot 2021-02-26 at 18 46 27" src="https://user-images.githubusercontent.com/5115677/109322239-1ab38480-7863-11eb-9e08-0280b02ee30c.png">
Do you think about this components?

**Comment by AnteaterKit** [comment]
https://user-images.githubusercontent.com/5115677/112388617-73f8c180-8d04-11eb-976a-058a6e1085dc.mov

**Comment by AnteaterKit** [comment]
Hi!
I am ready to discuss architecture of this component

**Comment by waterplea** [comment]
@AnteaterKit I don't think it should be a separate component. Because datalist is external and in full control of the developer it can be implemented on the app side. I've just created it here:
https://stackblitz.com/edit/taiga-tree-select

One issue is we need to programmatically update input of `tui-expand` and trigger change detection, but its `ChangeDetectorRef` is private. I wonder if it makes sense to make it public so these cases of multiple `tui-expand` in the loop can be solved in similar fashion.

**Comment by waterplea** [comment]
I've asked our designer if we need such component internally and he said he would think about it and if we do, he'd make an official design for it.

**Comment by AnteaterKit** [comment]
@waterplea Thank you for your example. 
I thought about more difficult solution:
like treeList in Core,   tree-select in CDK, but everything is easier and based on tuiDataList and hostedDropdown.

But my mind is a habit of work with material [CDK](https://material.angular.io/cdk/tree/overview) and ant design. They all have separate  treeView.

Your solution is more elegant and easy to use.

**Comment by waterplea** [comment]
Thank you 🙂 we need to kick @MarsiBarsi  so he would add his generic recursive component to Taiga UI so we can use it, it would probably simplify that example.

**Comment by MarsiBarsi** [comment]
Yeah, I remember about tree view. I'll announce a couple of live streams in the next month and add TreeView during them ;)

**Comment by AnteaterKit** [comment]
@MarsiBarsi It's cool info! Please add any example with 1) checked tree view 2) drag & drop items to swap item through nodes in treeView. It's very popular cases like hierarchical Car editor, or goods editor.
