### ISSUE TITLE
[FEATURE] Padding CSS vars

### ISSUE THREAD

**Issue by waterplea** [TinkoffCreditSystems/taiga-ui#386]
It would be great if we added CSS vars for paddings, at least for input fields as customizing those often requires changing padding.

**Comment by sean-perkins** [comment]
It'd be great if the foundation of the design system declared the system-level variables, but components sub-typed their own definition. 

For example, pretending this was in `variables.less`:
```
:root {
    --tui-spacing-xxxs: 0.125rem; // 2px
    --tui-spacing-xxs: 0.25rem; // 4px
    --tui-spacing-xs: 0.5rem; // 8px
    --tui-spacing-s: 0.75rem; // 12px
    --tui-spacing-m: 1rem; // 16px
    --tui-spacing-l: 1.25rem; // 20px
    --tui-spacing-xl: 1.75rem; // 28px
    --tui-spacing-xxl: 2.25rem; // 36px
    --tui-spacing-xxxl: 3rem; // 48px
    --tui-spacing-xxxxl: 4.5rem; // 72px
}
```

Then at an input component level stylesheet:
```
:host {
    --tui-input-padding: var(--tui-spacing-xxxs) var(--tui-spacing-m);
}
```

This would allow implementers to override the system rules of spacing (margins/paddings/gaps/etc.), but also have finite control over a component level's declaration. 

Based on another conversation for internal vs. global CSS classes, it could make sense to denote internal style variables with `--t-input-padding`.

I'm unsure of CSS' `::part` working with Angular's default view encapsulation (as it's requires a shadow tree I believe), but that could be another convenient way to expose the native input control to parent implementations, without having a bunch of CSS variables.

**Comment by waterplea** [comment]
Not sure what would be the purpose of local variables. Semantic naming?

**Comment by sean-perkins** [comment]
> Not sure what would be the purpose of local variables. Semantic naming?

They provide a convenient API for developers to override styles deeper than just host styling. This is a more common practice with web component libraries that I have seen (Ionic, Shoelace, etc.). With web components, you have the added complexity of shadom DOM that prevents developers from easily manipulating styles on inner nodes. With Angular and the standard view encapsulation, it also becomes slightly more difficult for developers to access and style elements in a specific context. 

I would argue for Taiga and inputs, it could make more sense to have root level style variables that implementers could override at a system level. Because you are directly using color variables like `--tui-text-02` for the background color, the only real path to customizing that for someone wanting a different default without changing the value of `--tui-text-02` at a system level is doing something like:

```
tui-primitive-textfield {
   --tui-text-02: #fff;
}
```

But the same CSS variable is used for overriding the hovered foreground color of the icon when not in a readonly state. So developers get more boxed in and can't easily re-use these awesome components in a more customized design system. 

If instead the primitive text field had local variables for:
```
:host {
   --tui-textfield-icon-color: var(--tui-text-02);
   --tui-textfield-background: var(--tui-text-02);
}
```

Implementers can fully customize how the primitive text field is themed in their own design system. There's quite a few components that fall into this; where they work/look great as long as you're theming an app that matches against the color scheme rules established. 

This pattern is also a little easier on new developers to Taiga or developers maintaining Taiga in their app; as it's not a bunch of targeted CSS selectors that are bound to change in the future.

Happy to chat more through this if you believe it has a place in Taiga or to run through a few examples 👍  Also completely understand if this is not what you want to do :)
