### ISSUE TITLE
[BUG] [Input] Postfix shown on top of input

### ISSUE THREAD

**Issue by hakimio** [TinkoffCreditSystems/taiga-ui#472]
# 🐞 Bug report

### Description

Dollar sign is shown on top of input in `Group` component demo.

### Reproduction

1. Open group component demo
2. Try typing some number in "How much?" input which has dollar sign postfix.

### Expected behavior

Dollar sign should not appear on top of input.

### Additional context

![dollar sign margin](https://user-images.githubusercontent.com/768105/121158657-d2850480-c84a-11eb-95f3-7ca07c8684d4.PNG)

**Comment by waterplea** [comment]
@hakimio this issue is linked to:
https://github.com/TinkoffCreditSystems/taiga-ui/issues/416
At the moment, there's no way to show postfix and right-align controls. In the original design, currency symbol is supposed to go to the table heading for the corresponding column. If you want to close this issue, you can change demo accordingly :)

**Comment by waterplea** [comment]
Removed this section from demo.
