### ISSUE TITLE
[BUG] Unavailable to use TuiTableBarsHostModule in unit tests

### ISSUE THREAD

**Issue by YaroslavTrubanov** [TinkoffCreditSystems/taiga-ui#491]
# 🐞 Bug report

### Description

I have component where i use TuiTableBarsService and use open() method in OnInit() hook. It works properly except unit tests (jest). In unit tests i get such error but both module and component exist in test.

Error: AssertionError [ERR_ASSERTION]: Table bars are disabled, enable support by adding TuiTableBarsHostModule to your main app module and tui-table-bars-host component to app template
at Observable._subscribe (../../../node_modules/@taiga-ui/addon-tablebars/bundles/ng:/@taiga-ui/addon-tablebars/services/table-bars.service.ts:20:23)

### Reproduction

1. Use TuiTableBarsService in component and open it in OnInit
2. Try to test it with import TuiTableBarsHostModule and using tui-table-bars-host in template
3. Get error

### Expected behavior

It should be possible to test tableBarsService in unit test

### Versions

-   OS: macOS
-   Browser chrome
-   Angular 11
-   Package @taiga-ui/addon-tablebars: 2.11.1

**Comment by waterplea** [comment]
The issue is caused by using `Subject` in `TableBarsService`. We need to switch it to `ReplaySubject` so if new table bar is opened before `async` subscription is initialized in the host, it would still get the replayed value. Assertion should probably be removed, since there's no way of telling if it's just too early or if there really is no host component.
