### ISSUE TITLE
[BUG] `DialogHost` breaks `canDeactivate` guard

### ISSUE THREAD

**Issue by nsbarsukov** [TinkoffCreditSystems/taiga-ui#631]
# 🐞 Bug report

### Description
In 2.13.0 [feature with closing dialogs on back navigation](https://github.com/TinkoffCreditSystems/taiga-ui/issues/451) was released. It breaks `canDeactivate` guard which calls confirm dialog (before leaving page user is asked if he is sure to leave page: if user confirm it, dialog sends `true` to `canDeactivate` function).
In this case, expected behavior is to execute back navigation if user confirms his action in dialog.
But actual behavior is guard calls dialog => `DialogHost` changes `window.history` => angular unsubscribes from observable inside `canDeactivate` (because history state which triggered guard is not already actual).

### Reproduction
1. Create `canDeactivate` guard which calls confirm dialog
2. Open dialog and click browser back navigation

### Expected behavior
Back navigation happens if user confirm his actions inside dialog (when async `true` value was send to `canDeactivate` function).

### Versions
-   @taiga-ui/cdk@2.13.0 or more

**Comment by dolgiyspb** [comment]
Example (check with "Open in new window", because [feature](https://github.com/TinkoffCreditSystems/taiga-ui/issues/451) doesn't work in iframe)

- Works with @taiga-ui v12: https://stackblitz.com/edit/taiga-starter-wxezzv
- Broken with @taiga-ui v14: https://stackblitz.com/edit/taiga-starter-uydvtm
