### ISSUE TITLE
[BUG] TuiTextArea's scroll doesn't disappear when area is cleared

### ISSUE THREAD

**Issue by mvoidsk** [TinkoffCreditSystems/taiga-ui#664]
# 🐞 Bug report

### Description

If I set tuiTextfieldSize = "m" and the minimum height, when the maximum number of lines is reached, the scroll appears and after when the field is cleared, the scroll remains and is not removed unless you manually scroll it to the very top of the field. 

### Reproduction

https://stackblitz.com/edit/taiga-starter-bxzek7?file=src%2Fapp%2Fapp.component.html

### Expected behavior

Expected scroll should be disappeared when area is cleared 

### Versions

-   OS: Windows 10
-   Browser Chrome
-   Angular 10
-   Package @taiga-ui/kit@2.13.1

**Comment by nsbarsukov** [comment]
It is problem of `<tui-scrollbar />` inside `<tui-text-area />` .
When we set `m`-size + `min-height: 44px !important;` for text-area, you will leave only 20px for text inside it (apart from paddings + margins). This text is wrapped by `<tui-scrollbar />` (which has controls with min-height: 24px).

When you make many rows => scrollbar appears.
After removing all texts => scroll controls dont disappear (although the text-container's height is zero) because [in this code line](https://github.com/TinkoffCreditSystems/taiga-ui/blob/main/projects/core/components/scroll-controls/scroll-controls.component.ts#L63) **client-height** is 20px but **scroll-height** is 24px (min-height of scroll-bar-controls).

# Minimum reproduction (without text-area)
https://stackblitz.com/edit/scrollbar-bug-issue
Scroll is not removed after clicking `One row` button.
HTML:
```
<tui-scrollbar
	class="tui-text_body-xs tui-space_top-5 tui-space_bottom-5"
	style="min-height: 20px; max-height: 80px"
>
	<span>{{text}}</span>
</tui-scrollbar>

<button tuiButton (click)="toOneRow()">One row</button>
<button tuiButton (click)="toManyRow()">Many rows</button>
```

TS:
```
export class AppComponent {
  text = `Many Many many many words`.repeat(50);

  toOneRow() {
      this.text = '  ';
  }

  toManyRow() {
      this.text = `Many Many many many words`.repeat(50);
  }
}
```
