### ISSUE TITLE
Ability to specify a prefix for InputNumber field

### ISSUE THREAD

**Issue by nthonymiller** [TinkoffCreditSystems/taiga-ui#78]
# 🚀 Feature request

### Is your feature request related to a problem?

No

### Describe the solution you'd like

Ability to show currency symbol at the beginning of a number input field rather than just a suffix.

### Additional context

The InputNumber component currently displays currency symbol at the end using the [postfix] property, which depending on the country this might be fine, but would be great to have the ability to specify a [prefix] property value where this would be fixed to the left and data entry would occur after this value.

**Comment by MarsiBarsi** [comment]
Hey Anthony 👋

Thank you for this issue, we'll do prefix for all inputs 👍

**Comment by jonsamwell** [comment]
Any update on this? I could potentially help with a PR for this but it looks like it would be modifying the `primitive-textfield` all the way down in core so might not be a good first PR? Advice appreciated.

**Comment by waterplea** [comment]
Yes, it's a pretty complicated feature. Postfix is easy because we just make an invisible span with the same value that pushes postfix to the side automagically. Here we would need to recalculate left padding of an input and while it's not technically hard, it's a fairly low-level DOM reach, something we generally try to avoid. It's also tied to [this issue](https://github.com/TinkoffCreditSystems/taiga-ui/issues/416), because in text-align to the right everything is reversed :)

I'm not ready yet to think about it.

**Comment by jonsamwell** [comment]
@waterplea thanks for the reply and understand this is a tough one.  I would really like to see this so let me know if there is any other bit of easier functionality I could do to help you along with this one.

**Comment by jonsamwell** [comment]
@waterplea awesome work thank you very much for this!
