### ISSUE TITLE
[FEATURE] DataGrid, Tree, TreeTable, Org chart

### ISSUE THREAD

**Issue by ramax495** [TinkoffCreditSystems/taiga-ui#93]
Are you going to implement something from the list below ?

Examples from NgPrime components: 
OrganizationChart - https://www.primefaces.org/primeng/showcase/#/organizationchart
Tree - https://www.primefaces.org/primeng/showcase/#/tree
DataGrid with sorting, filtering, editing, local and remote datasource - https://www.primefaces.org/primeng/showcase/#/table
TreeTable - https://www.primefaces.org/primeng/showcase/#/treetable

**Comment by waterplea** [comment]
`OrganizationChart` is not something we had a need internally so it's not on the horizon.
`Tree` should be pretty easy to implement, we would add it at some point most likely. 
`DataGrid` is our next big task to work on once we finish up transitioning proprietary projects to open source library.
`TreeTable` - not sure about that. It's not in the design for `DataGrid` at this point.

Such questions are more suitable for Discussions section of GitHub, as Issues are for concrete feature requests. Feel free to open separate feature requests, if you want. I'll open one for `DataGrid` which is called `Table` in our internal designs since it's something we will work on soon for sure.

**Comment by waterplea** [comment]
See https://github.com/TinkoffCreditSystems/taiga-ui/issues/95

**Comment by FloMaetschke** [comment]
Hi, is there any update on the datagrid next big thing?
Just asking because it is 2025. :)

**Comment by waterplea** [comment]
Like I said, the `DataGrid` is `Table` and it's available here:
https://taiga-ui.dev/components/table
We also have Tree:
https://taiga-ui.dev/components/tree

**Comment by FloMaetschke** [comment]
Hello, thank you for the quick reply.
Please do not misunderstand. I'm just looking for a new UI lib for my project and I really like taiga-ui so far. 
However, I also need a datagrid with a certain standard set of functions.

I have seen that you can do the following with taiga-ui:

- Edit Data
- Custom Cell Content
- Sort Column
- Filter (externally ui)
- Resize Column
- Move Rows
- Add Rows/Cols Dynamically
- Row Grouping
- Virtual Scroll
- Selectable Rows
- Footer
- Pagination

What I am still missing:

- Basic Column Filter (e.g. Textbox in Column Header)
- Advanced Column Filter (Icon and Popup)
- Static Rows and Cols (Top, Bottom, Left, Right)
- Row Expansion
- Striped Rows
- Row Grouping
- Row Span

- Button in the corner for grid properties maybe (e.g. Toggle Columns, Order, etc. i saw that at ag-grid, but this is just chrome)

I may have overlooked one of the functions in taiga-ui table. 
For the table component, an example that can display all primary functions at once would be good.

Will the table continue to be developed or is this function set currently over? I mean, you'll have thought about something.

**Comment by waterplea** [comment]
Taiga UI is a low level library, there's no built-in features like you listed, sorry.
